---
sidebar: sidebar 
permalink: concept-replication.html 
keywords: ontap, cluster, discover, manage, BlueXP, bluexp, hybrid cloud, replication policy, policy, replication, replicating, snapmirror, snapvault, data replication, fanout, cascade, source, destination, disaster recovery, DR, archive, archiving, retention, netapp replication 
summary: O NetApp SnapMirror replica dados em alta velocidade via LAN ou WAN, para que você tenha alta disponibilidade de dados e rápida replicação de dados em ambientes virtuais e tradicionais.  Quando você replica dados para sistemas de armazenamento NetApp e atualiza continuamente os dados secundários, seus dados são mantidos atualizados e permanecem disponíveis sempre que você precisar deles. Não são necessários servidores de replicação externos. 
---
= Saiba mais sobre a NetApp Replication
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O NetApp SnapMirror replica dados em alta velocidade via LAN ou WAN, para que você tenha alta disponibilidade de dados e rápida replicação de dados em ambientes virtuais e tradicionais.  Ao replicar dados para sistemas de armazenamento NetApp usando o NetApp Replication e atualizar continuamente os dados secundários, seus dados são mantidos atualizados e permanecem disponíveis sempre que você precisar deles. Não são necessários servidores de replicação externos.



[[netapp-console]]
== NetApp Console

A NetApp Replication pode ser acessada por meio do NetApp Console.

O Console oferece gerenciamento centralizado de NetApp storage e serviços de dados em ambientes locais e em nuvem, com nível de qualidade empresarial. O Console é necessário para acessar e usar NetApp data services. Como interface de gerenciamento, ele permite que você gerencie muitos recursos de storage a partir de uma única interface. Os administradores do Console podem controlar o acesso ao storage e aos serviços para todos os sistemas da empresa.

Você não precisa de licença ou assinatura para começar a usar o Console. As cobranças só ocorrem quando você precisa implantar agentes do Console na sua nuvem para garantir a conectividade com seus sistemas de storage ou NetApp data services. No entanto, alguns NetApp data services acessíveis pelo Console exigem licença ou assinatura.

Saiba mais sobre o  https://docs.netapp.com/us-en/console-setup-admin/concept-overview.html["NetApp Console"].



[[features]]
== Características

* Replique dados entre sistemas de armazenamento ONTAP para dar suporte a backup e recuperação de desastres na nuvem ou entre nuvens.
* Garanta a confiabilidade do seu ambiente de DR com alta disponibilidade.
* A replicação eficiente em nível de bloco entre o sistema de storage ONTAP é rápida e eficiente, com pontos de recuperação granulares tanto para recuperação de desastres quanto para backup.




[[cost]]
== Custo

A NetApp não cobra pelo uso do NetApp Replication, mas você precisará verificar com seu provedor de nuvem as taxas de entrada e saída de dados aplicáveis.



[[supported-systems]]
== Sistemas suportados

O NetApp Replication permite a replicação de dados entre os seguintes tipos de sistemas.

[cols="30,30"]
|===
| Sistema de origem | Sistemas de destino suportados 


| Cloud Volumes ONTAP  a| 
* Amazon FSx para ONTAP
* Cloud Volumes ONTAP
* cluster ONTAP local




| cluster ONTAP local  a| 
* Amazon FSx para ONTAP
* Cloud Volumes ONTAP
* cluster ONTAP local




| Amazon FSx para ONTAP  a| 
* Amazon FSx para ONTAP
* Cloud Volumes ONTAP
* cluster ONTAP local


|===


[[how-data-replication-works]]
== Como funciona a replicação de dados

NetApp Replication simplifica a replicação de dados entre volumes em sistemas ONTAP separados usando as tecnologias SnapMirror e SnapVault. Para configurar a replicação, você só precisa identificar o volume de origem e o volume de destino e, em seguida, escolher uma política de replicação e um agendamento.

Para o Cloud Volumes ONTAP, o NetApp Replication compra os discos necessários, configura relacionamentos, aplica a política de replicação e, em seguida, inicia a transferência de linha de base entre os volumes.


NOTE: A transferência de linha de base inclui uma cópia completa dos dados de origem.  Transferências subsequentes contêm cópias diferenciais dos dados de origem.



[[supported-data-protection-configurations]]
== Configurações de proteção de dados suportadas

O NetApp Replication oferece suporte a configurações de proteção de dados simples, em fanout e em cascata:

* Em uma configuração simples, a replicação ocorre do volume A para o volume B.
* Em uma configuração fanout, a replicação ocorre do volume A para vários destinos.
* Em uma configuração em cascata, a replicação ocorre do volume A para o volume B e do volume B para o volume C.




[[replicate-data-using-netapp-backup-and-recovery]]
== Replique dados usando o NetApp Backup and Recovery

link:https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["NetApp Backup and Recovery"^] permite que você replique dados entre volumes em sistemas ONTAP separados, ao mesmo tempo em que cria backups dos mesmos dados para o storage de objetos. Se você quiser gerenciar a replicação e a proteção de backup para objeto para os mesmos dados do ONTAP em um único serviço, considere usar o NetApp Backup and Recovery.

NetApp Replication oferece suporte aos seguintes recursos que não estão disponíveis no NetApp Backup and Recovery.

* O NetApp Backup and Recovery atualmente não oferece suporte à replicação de dados de ou para sistemas FSx for ONTAP.
* O NetApp Backup and Recovery não oferece suporte à criação de uma replicação única de um volume.


Além disso, os relacionamentos em cascata são mais fáceis de configurar na Replicação. Se você precisar de alguma dessas funcionalidades, use a NetApp Replicação.
